### ISSUE TITLE
Fehler 

### ISSUE THREAD

**Issue by deubadario** [FACT-Finder-Web-Components/shopware6-plugin#98]
Hello, 

we have multiple error with the plugin version 4.0

The Error occurs on plugin activation.

[2022-11-15T13:46:24.510323+00:00] php.CRITICAL: Uncaught Error: Call to a member function getCustomer() on null {"exception":"[object] (Error(code: 0): Call to a member function getCustomer() on null at /var/www/html/vendor/omikron/shopware6-factfinder/src/Subscriber/BeforeSendResponseEventSubscriber.php:41)"} []

![factfinder_4_0](https://user-images.githubusercontent.com/106805244/201942084-96ef047c-26d6-4384-bbc7-06215962db32.PNG)

**Comment by grzegorz-jamroz** [comment]
Hi @deubadario we have released new SDK version [v4.0.1](https://github.com/FACT-Finder-Web-Components/shopware6-plugin/releases/tag/v4.0.1). Unfortunately we are not able to reproduce your error but base on provided error log we have added fixes.

**Comment by deubadario** [comment]
Hi @grzegorz-jamroz the Plugin is still not working, the same error ocurs on activation. I'm sure more complains will follow because I tried the plugin with a clean Shopware 6 installation with only FactFinder Plugin and still the same problem. 


Shopware v. 6.4.14.0
Plugin v. 4.0 + 4.0.1

Logs:
[2022-11-21T07:26:31.195441+00:00] php.CRITICAL: Uncaught Error: Call to a member function getCustomer() on null {"exception":"[object] (Error(code: 0): Call to a member function getCustomer() on null at /var/www/html/vendor/omikron/shopware6-factfinder/src/Subscriber/BeforeSendResponseEventSubscriber.php:45)"} []
[2022-11-21T07:26:31.195780+00:00] request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function getCustomer() on null" at /var/www/html/vendor/omikron/shopware6-factfinder/src/Subscriber/BeforeSendResponseEventSubscriber.php line 45 {"exception":"[object] (Error(code: 0): Call to a member function getCustomer() on null at /var/www/html/vendor/omikron/shopware6-factfinder/src/Subscriber/BeforeSendResponseEventSubscriber.php:45)"} []

**Comment by grzegorz-jamroz** [comment]
@deubadario could you try with dev branch:
```
composer require omikron/shopware6-factfinder:dev-v1-FFWEB-2622-activation-error 
```

I have added here another fix. I don't want to make release for each of them before we settle final solution.

**Comment by deubadario** [comment]
@grzegorz-jamroz Session Problem

Session has not been set:  

BeforeSendResponseEventSubscriber.php  L 114

  $session  = $request->getSession();

Logs:

{"errors":[{"code":"0","status":"500","title":"Internal Server Error","detail":"Session has not been set.","meta":{"trace":[{"file":"\/var\/www\/html\/vendor\/omikron\/shopware6-factfinder\/src\/Subscriber\/BeforeSendResponseEventSubscriber.php","line":114,"function":"getSession","class":"Symfony\\Component\\HttpFoundation\\Request","type":"-\u003E"},{"file":"\/var\/www\/html\/vendor\/symfony\/event-dispatcher\/Debug\/WrappedListener.php","line":117,"function":"hasCustomerJustLoggedOut","class":"Omikron\\FactFinder\\Shopware6\\Subscriber\\BeforeSendResponseEventSubscriber","type":"-\u003E"},{"file":"\/var\/www\/html\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":230,"function":"__invoke","class":"Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener","type":"-\u003E"},{"file":"\/var\/www\/html\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":59,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E"},{"file":"\/var\/www\/html\/vendor\/shopware\/core\/Content\/Flow\/Dispatching\/FlowDispatcher.php","line":51,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E"},{"file":"\/var\/www\/html\/vendor\/shopware\/core\/Framework\/Webhook\/WebhookDispatcher.php","line":96,"function":"dispatch","class":"Shopware\\Core\\Content\\Flow\\Dispatching\\FlowDispatcher","type":"-\u003E"},{"file":"\/var\/www\/html\/vendor\/shopware\/core\/Framework\/Event\/BusinessEventDispatcher.php","line":53,"function":"dispatch","class":"Shopware\\Core\\Framework\\Webhook\\WebhookDispatcher","type":"-\u003E"},{"file":"\/var\/www\/html\/vendor\/shopware\/core\/Framework\/Event\/NestedEventDispatcher.php","line":35,"function":"dispatch","class":"Shopware\\Core\\Framework\\Event\\BusinessEventDispatcher","type":"-\u003E"},{"file":"\/var\/www\/html\/vendor\/symfony\/event-dispatcher\/Debug\/TraceableEventDispatcher.php","line":154,"function":"dispatch","class":"Shopware\\Core\\Framework\\Event\\NestedEventDispatcher","type":"-\u003E"},{"file":"\/var\/www\/html\/vendor\/shopware\/core\/HttpKernel.php","line":157,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher","type":"-\u003E"},{"file":"\/var\/www\/html\/vendor\/shopware\/core\/HttpKernel.php","line":79,"function":"doHandle","class":"Shopware\\Core\\HttpKernel","type":"-\u003E"},{"file":"\/var\/www\/html\/public\/index.php","line":74,"function":"handle","class":"Shopware\\Core\\HttpKernel","type":"-\u003E"}],"file":"\/var\/www\/html\/vendor\/symfony\/http-foundation\/Request.php","line":739}}]}


[2022-11-21T09:24:13.393884+00:00] php.CRITICAL: Uncaught Exception: Session has not been set. {"exception":"[object] (Symfony\\Component\\HttpFoundation\\Exception\\SessionNotFoundException(code: 0): Session has not been set. at /var/www/html/vendor/symfony/http-foundation/Request.php:739)"} []
[2022-11-21T09:24:13.396601+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpFoundation\Exception\SessionNotFoundException: "Session has not been set." at /var/www/html/vendor/symfony/http-foundation/Request.php line 739 {"exception":"[object] (Symfony\\Component\\HttpFoundation\\Exception\\SessionNotFoundException(code: 0): Session has not been set. at /var/www/html/vendor/symfony/http-foundation/Request.php:739)"} []

**Comment by grzegorz-jamroz** [comment]
@deubadario ok fix added please pull changes

**Comment by grzegorz-jamroz** [comment]
by the way thank you for your help :)

**Comment by deubadario** [comment]
@grzegorz-jamroz no problem!

The Plugin can be installed now without errors.

But I've found another issue.

The search is working correctly with the version 3.1.1 
but  4.0., 4.0.1 and in dev-FFWEB-2622-activation-error display the same results, but the category link is not working.

Can you please check or should I create another Ticket?

**Comment by grzegorz-jamroz** [comment]
@deubadario I pushed changes to `dev-FFWEB-2622-activation-error`

Please let me now does it help?

**Comment by deubadario** [comment]
@grzegorz-jamroz sry but this is not acceptable. I'm a client and I think I did enough testing, I'm sure you have deployment protocols and intern testers. Please let me know when the issue is fixed and rolled out.

Thank you!

**Comment by grzegorz-jamroz** [comment]
Hi @deubadario, we have released new version [v4.0.2](https://github.com/FACT-Finder-Web-Components/shopware6-plugin/releases/tag/v4.0.2)

It solves problem with SDK activation and also problem with category page.

Thank you! :)
